  export const mockSalesData = {
    "2022": [
      { month: 'January', value: 100 },
      { month: 'February', value: 150 },
      { month: 'March', value: 200 },
      { month: 'April', value: 180 },
      { month: 'May', value: 220 },
      { month: 'June', value: 250 },
      { month: 'July', value: 300 },
      { month: 'August', value: 280 },
      { month: 'September', value: 30 },
      { month: 'October', value: 350 },
      { month: 'November', value: 380 },
      { month: 'December', value: 400 },
    ],

    "2023": [
      { month: 'January', value: 130 },
      { month: 'February', value: 15 },
      { month: 'March', value: 210 },
      { month: 'April', value: 188 },
      { month: 'May', value: 122 },
      { month: 'June', value: 60 },
      { month: 'July', value: 90 },
      { month: 'August', value: 28 },
      { month: 'September', value: 133 },
      { month: 'October', value: 350 },
      { month: 'November', value: 380 },
      { month: 'December', value: 400 },
    ],
    "2024": [
      { month: 'January', value: 230 },
      { month: 'February', value: 145 },
      { month: 'March', value: 110 },
      { month: 'April', value: 188 },
      { month: 'May', value: 12 },
      { month: 'June', value: 60 },
      { month: 'July', value: 90 },
      { month: 'August', value: 208 },
      { month: 'September', value: 153 },
      { month: 'October', value: 350 },
      { month: 'November', value: 380 },
      { month: 'December', value: 110 },
    ]
  }
    
  export const mockRevenueData = {
    "2022": [
      { month: 'January', value: 5000 },
      { month: 'February', value: 6000 },
      { month: 'March', value: 7000 },
      { month: 'April', value: 6500 },
      { month: 'May', value: 7500 },
      { month: 'June', value: 8000 },
      { month: 'July', value: 9000 },
      { month: 'August', value: 8500 },
      { month: 'September', value: 9500 },
      { month: 'October', value: 10000 },
      { month: 'November', value: 11000 },
      { month: 'December', value: 12000 }
    ],
    "2023": [
      { month: 'January', value: 10000 },
      { month: 'February', value: 4000 },
      { month: 'March', value: 5000 },
      { month: 'April', value: 1500 },
      { month: 'May', value: 8500 },
      { month: 'June', value: 8600 },
      { month: 'July', value: 9600 },
      { month: 'August', value: 9500 },
      { month: 'September', value: 1500 },
      { month: 'October', value: 16000 },
      { month: 'November', value: 12000 },
      { month: 'December', value: 13900 }
    ],
    "2024": [
      { month: 'January', value: 7000 },
      { month: 'February', value: 4000 },
      { month: 'March', value: 2000 },
      { month: 'April', value: 6500 },
      { month: 'May', value: 8500 },
      { month: 'June', value: 3600 },
      { month: 'July', value: 5600 },
      { month: 'August', value: 1500 },
      { month: 'September', value: 4500 },
      { month: 'October', value: 8000 },
      { month: 'November', value: 3000 },
      { month: 'December', value: 2900 }
    ],
  }
  
  export const mockUserActivityData = {
    "2022": [
      { month: 'Jan', value: 100 },
    { month: 'Feb', value: 120 },
    { month: 'Mar', value: 130 },
    { month: 'Apr', value: 100 },
    { month: 'May', value: 120 },
    { month: 'Jun', value: 130 },
    { month: 'Jul', value: 100 },
    { month: 'Aug', value: 130 },
    { month: 'Sept', value: 120 },
    { month: 'oct', value: 130 },
    { month: 'Nov', value: 100 },
    { month: 'Dec', value: 120 },
    ],
    "2023": [
      { month: 'Jan', value: 200 },
      { month: 'Feb', value: 320 },
      { month: 'Mar', value: 430 },
      { month: 'Apr', value: 200 },
      { month: 'May', value: 120 },
      { month: 'Jun', value: 530 },
      { month: 'Jul', value: 200 },
      { month: 'Aug', value: 330 },
      { month: 'Sept', value: 120 },
      { month: 'oct', value: 230 },
      { month: 'Nov', value: 130 },
      { month: 'Dec', value: 170 },
    ],
    "2024": [
      { month: 'Jan', value: 500 },
      { month: 'Feb', value: 220 },
      { month: 'Mar', value: 730 },
      { month: 'Apr', value: 300 },
      { month: 'May', value: 920 },
      { month: 'Jun', value: 430 },
      { month: 'Jul', value: 600 },
      { month: 'Aug', value: 230 },
      { month: 'Sept', value: 720 },
      { month: 'oct', value: 330 },
      { month: 'Nov', value: 730 },
      { month: 'Dec', value: 170 },
    ],
  };
  